# Generated by Django 4.2.3 on 2023-07-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
